name: test action

on: 
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: |
          echo "My first github action"
          
